### PR TITLE
Update URL in gemspec

### PR DESCRIPTION
**Pull request by wwood**
Hi,

I'm attempting to package `event-bus` for the GNU Guix package manager, and had some trouble finding this repository, see https://github.com/cucumber/aruba/issues/334

Thanks,
ben

### CODE REVIEW

**Comment by dg-ratiodata** [comment]
Sorry, I saw your PR to late and changed the gemspec along with all other urls.

**Comment by dg-ratiodata** [comment]
Thanks anyway.

**Comment by wwood** [comment]
No problem, thanks for being a responsive maintainer.

**Comment by dg-ratiodata** [comment]
You're welcome! Give me a ping if you've got problems packaging aruba - best by file an issue or for questions you can use https://gitter.im/cucumber/aruba.

**Comment by dg-ratiodata** [comment]
@wwood This gem will be "re-integrated" into `aruba`-core. Please see https://github.com/fedux-org/event-bus/issues/6

**Comment by mattwynne** [comment]
I'm not so sure that re-integration is as important for Aruba. It's up to you. Cucumber is frequently loaded into the same Ruby process as the system under test. I think that is much more rare for Aruba. So clashing namespaces are much less of an issue.

**Comment by dg-ratiodata** [comment]
Yeah, but the only reason for creating that gem was the re-use of code in cucumber and aruba. Having this gem I need to maintain two gems, two repositories, packagers need to package another dependency. Re-integrating was not a great deal for me. I have already finsihed it. This gem is now obsolete.

**Comment by dg-ratiodata** [comment]
Maybe, I write a short article and see if someone is interested in such a gem.

**Pull request closed without merging**
